[package]
name = "sqs_experiment"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "sqs-sender"
path = "src/sqs_sender.rs"

[dependencies]
docopt = "0.7"
rusoto = {version = "0.23", features = ["sqs"]}
rustc-serialize = "0.3"
